### ISSUE TITLE
Error loading GTFS file

### ISSUE THREAD

**Issue by ditsonda** [Transitime/core#28]
I'm testing Transitime for the transport system of Santiago of Chile.

I downloaded the latest version of Transitime, December 23, commit 464a055b5ba5d69f1fe0f22c4a50e3be10d686c7. But this aborts loading the GTFS file
(http://datos.gob.cl/dataset/8583ae05-d62f-42d7-a56d-4f865711b65a/resource/dc31a5c7-e717-4b9d-a9a6-93b4d4d2aaca/download/gtfsv17.zip).

The error says:

14:02:14.139 WARN  - Modifying headsign "(M) La Cisterna" to "(M) La Cisterna to PG1583 - Parada  / Est. Intermodal   La Cisterna" since it has a different last stop. TripPattern H
erna" direction 1 from stop PF152 to stop PG1583. Other TripPattern Headsign "(M) La Cisterna" direction 1 from stop PF152 to stop PG1573
Exception in thread "main" java.lang.NullPointerException
        at org.transitime.gtfs.GtfsData.makeHeadsignsUniqueIfDifferentLastStop(GtfsData.java:1501)
        at org.transitime.gtfs.GtfsData.createTripsAndTripPatterns(GtfsData.java:1469)
        at org.transitime.gtfs.GtfsData.processStopTimesData(GtfsData.java:1118)
        at org.transitime.gtfs.GtfsData.processData(GtfsData.java:2537)
        at org.transitime.applications.GtfsFileProcessor.process(GtfsFileProcessor.java:294)
        at org.transitime.applications.GtfsFileProcessor.main(GtfsFileProcessor.java:642)

**Comment by skibu** [comment]
Appears that can have a route configured without any trips/trip patterns. For this situation needed to skip such a route to avoid a NPE. Current version of code d11b14d has fix.

**Comment by ditsonda** [comment]
Thanks skibu!!! It worked
