### ISSUE TITLE
First run of GTFSFileProcessor seems to require at least one agency already populated in database.

### ISSUE THREAD

**Issue by scrudden** [Transitime/core#4]
This is the stack trace produced when first run with empty agency table.

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:635)
    at java.util.ArrayList.get(ArrayList.java:411)
    at org.transitime.gtfs.DbConfig.getFirstAgency(DbConfig.java:705)
    at org.transitime.applications.Core.<init>(Core.java:130)
    at org.transitime.applications.Core.createCore(Core.java:184)
    at org.transitime.applications.Core.getInstance(Core.java:197)
    at org.transitime.db.structs.Trip.getRoute(Trip.java:832)
    at org.transitime.db.structs.Trip.getRouteName(Trip.java:848)
    at org.transitime.db.structs.Trip.getRouteShortName(Trip.java:819)
    at org.transitime.gtfs.ScheduleBasedTravelTimesProcessor.determineTravelTimesBasedOnSchedule(ScheduleBasedTravelTimesProcessor.java:270)
    at org.transitime.gtfs.ScheduleBasedTravelTimesProcessor.processTrips(ScheduleBasedTravelTimesProcessor.java:474)
    at org.transitime.gtfs.ScheduleBasedTravelTimesProcessor.process(ScheduleBasedTravelTimesProcessor.java:568)
    at org.transitime.gtfs.GtfsData.processData(GtfsData.java:2344)
    at org.transitime.applications.GtfsFileProcessor.process(GtfsFileProcessor.java:254)
    at org.transitime.applications.GtfsFileProcessor.main(GtfsFileProcessor.java:604)

**Comment by skibu** [comment]
This was an issue introduced 4 weeks ago but fixed 3 days ago. In a logging message the GTFS processing software was trying to access data (the route name) that is only available to the core predictor system. But the core predictor system couldn't yet access that data since it wasn't yet in the database.

Solution is to simply pull in latest version of code which has the fix for ScheduleBasedTravelTimesProcessor class.
